### ISSUE TITLE
Tutorial setup chapter unclear sentence

### ISSUE THREAD

**Issue by pfontain** [KhronosGroup/OpenXR-Tutorials#100]
I find the sentence "There are both compile and runtime checks to select the requested Graphics API, and we construct an appropriate derived class through the use of ``std::unique_ptr<>``" a little unclear.

**Comment by AndrewRichards-Code** [comment]
Hi @pfontain,

The compile-time checks are controlled by the `XR_TUTORIAL_USE_...` pre-processor statements, which are set up by the `CMakeLists.txt`, and the runtime checks are done by the `CheckGraphicsAPI_TypeIsValidForPlatform()` function in `GraphicsAPI.cpp`. I hope this helps.

**Comment by pfontain** [comment]
Created https://github.com/KhronosGroup/OpenXR-Tutorials/pull/118 to add some of this information.

**Comment by rbessems** [comment]
Thanks Paul, your MR has been merged!

**Comment by pfontain** [comment]
You're welcome. It's Paulo ;)

**Comment by rbessems** [comment]
Thanks **Paulo** :)
