### ISSUE TITLE
GFX/OS falls off in FF when too narrow

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#102]

**Comment by rbessems** [comment]
Also needs a drop down icon like a triangle

**Comment by rvkennedy** [comment]
I've added a drop-down triangle that changes angle when hovered.

**Comment by AndrewRichards-Code** [comment]
88fb15a sets the max-width to 240px, which does address the issue in Firefox and other narrow-width mobile devices. Below 240px wide, the main text becomes impractical to read, so I think this is a sensible solution.

**Comment by AndrewRichards-Code** [comment]
78baa105 fixes the drop-down triangle issue on mobile devices by using this `.svg`: https://en.wikipedia.org/wiki/File:Vector_down_arrow_link.svg (Public Domain).
