### ISSUE TITLE
Release Version Change

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/OpenXR-Tutorials#104]
The first public release of the tutorial needs to be version 1.0._x_; where _x_ may be non-zero to indicate last minute changes.

Draft releases should be 0._N_._M_, where _N_ is incremented with each significant change and _M_ is for minor updates within that change.

I understand that the current state is really a beta release. The appropriate version number is of the form 1.0._x_-beta._N_; where _x_ is as above and _N_ is the release number. 

I believe that for this documentation and the work that is happening, we are at a draft release and just about to go to beta. The current release should be of the form 0._J_._K_ where J > 0 and K is the current patch. You can start with `0.5.10` (based on current patch #). Once all of the issues are resolved (except this one), the release shall be `1.0.0-beta.1`. Any changes from that release would increment the second 0 (e.g., from 1.0.0 to 1.0.1) and possibly the beta #.

**Comment by AndrewRichards-Code** [comment]
Thank you for all the information on the version numbering schemes for draft and beta release.
At the moment, the latest tag release is [`v0.0.13`](https://github.com/KhronosGroup/OpenXR-Tutorials/releases/tag/v0.0.13), so our one next will be `v0.5.14` as a draft release.
