### ISSUE TITLE
Android/Vulkan is duplicated 

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#105]
It appears that at the top level we have a full version of the website for vulkan/android. This site is then also duplicated at https://openxr-tutorial.com/android/vulkan/.

The top level pages should not be a full website but just links into the sub pages.

If the user does not make any explicit choice then the default sub page to go to is vulkan/android.

**Comment by rvkennedy** [comment]
Seems to be a spurious sphinx-build call in build-site.sh at the top.

**Comment by rvkennedy** [comment]
Fixed in a6cca832a03235641c5658f474a303c6b33df375

**Comment by rbessems** [comment]
confirmed
