### ISSUE TITLE
OS Selector without Graphics

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/OpenXR-Tutorials#110]
When the OS is identified without a graphics system (e.g., https://openxr-tutorial.com//windows/) the web server generates a 403 error. This page should redirect to .../vulkan. The solution could be a .htaccess file that redirects URLs using mod_rewrite, a redirect HTML page, or about 20 other mechanisms.

**Comment by AndrewRichards-Code** [comment]
c7e93b96 and a444de54 resolve this issue by adding a redirect `index.html` file in the OS folder of the site build.
