### ISSUE TITLE
Broken "Next" button on the front page of https://openxr-tutorial.com/

### ISSUE THREAD

**Issue by xwovr** [KhronosGroup/OpenXR-Tutorials#113]
There is a "Next" button on the front page (https://openxr-tutorial.com/). Click it opens https://openxr-tutorial.com/1-introduction.html which doesn't exist.

![Screenshot 2024-01-25 at 10 22 30 AM](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/28540225/ab3ace94-7d20-4212-af75-18651a554b21)

**Comment by rbessems** [comment]
Fixed with PR115
