### ISSUE TITLE
Add separate page with license and legal clauses GDPR, cookies etc

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#13]

**Comment by DrX3D** [comment]
Is there a target domain for the tutorials (e.g., tutorials.openxr.khronos.org)? Using *.khronos.org may make it easier because Khronos has a legal notice page (https://www.khronos.org/legal/privacy).

A request has been sent to WebServices for general text.

**Comment by rvkennedy** [comment]
@rbessems awaiting the text for this. Also, what licence should the website source text be under?

**Comment by DrX3D** [comment]
In the site footer, please add the following text.

"OpenXR Tutorial is a Khronos owned and operated site. Khronos [Legal Notices](https://www.khronos.org/legal/), [Privacy Policy](https://www.khronos.org/legal/privacy), and [Code of Conduct](https://www.khronos.org/about/code-of-conduct) apply.

**Comment by rvkennedy** [comment]
Done.
