### ISSUE TITLE
Hand tracking without controllers

### ISSUE THREAD

**Issue by gkarpa** [KhronosGroup/OpenXR-Tutorials#132]
Hi,
in chapter 5.1 where the hand tracking extensions are used and the hands are rendered as cuboids, it seems like the intention is to track & render the hands when the user is not holding the controllers. However, when I run it in pcvr with a Quest3 & SteamVR runtime, I get the rendering of the cuboids only when I'm holding the controllers. Have I misunderstood something? Thanks in advance!

**Comment by korejan** [comment]
If you're using oculus-link for streaming you'll need to set oculus-link's PC OpenXR runtime as the active runtime, enable "developer runtime features" (you need dev account linked), oculus-link's OpenVR driver doesn't support hand-tracking so you wont get support for it through SteamVR's OpenXR runtime.

**Comment by gkarpa** [comment]
Hi @korejan , thanks for the info. I am using the Steam Link app for the streaming and not Oculus link. Coincidentally enough, since version 2.8.3 of SteamVR and version 2.0.11.1197 of Steam Link, they did

> Enable hand-tracking pass through for SteamVR Input and XR_EXT_hand_tracking

so now it seems to be working nicely.

**Comment by rbessems** [comment]
Closing issue as it appears resolved.
