### ISSUE TITLE
Monado pre-built can be downloaded from the CI system

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#15]
Instead of describing how to build monado for windows just instruct them to download the CI binaries:

Windows: https://gitlab.freedesktop.org/monado/monado/-/jobs/44532444/artifacts/download?file_type=archive

**Comment by rvkennedy** [comment]
Thanks, testing this now.

**Comment by ChristophHaag** [comment]
Just saw this issue. I recently typed up these basic steps how one could use the monado ci build on windows.

Feel free to use and modify any part you find useful.

> Go to a pipeline and download the artifacts from the `windows` job. Or more conveniently, [this link always downloads to the latest windows build artifacts from the main branch](https://gitlab.freedesktop.org/monado/monado/-/jobs/artifacts/main/download?job=windows)
> 
> Extract the zip file. The following presumes that the archive is extracted in `C:\<USERNAME>\Downloads\artifacts` where powershell expands `$env:USERPROFILE` to the `C:\<USERNAME>` path, so when extracting it elsewhere, change `$env:USERPROFILE` accordingly.
> 
> In powershell, set desired environment variables like for example `$env:P_OVERRIDE_ACTIVE_CONFIG="remote"` to activate monado's `remote` driver. From the same shell, run `& $env:USERPROFILE\Downloads\artifacts\install\bin\monado-service.exe` (the call operator `&` is necessary when starting an application with a variable like USERPROFILE in the path).
> 
> To run an OpenXR application like hello_xr (which is found in the [openxr_loader_windows-1.0.28.zip from the OpenXR-SDK-Source releases](https://github.com/KhronosGroup/OpenXR-SDK-Source/releases)) there are two ways:
> 
> 1. Set the active runtime entry in the registry to the artifacts\install\openxr_monado.json file. Then starting any standard OpenXR application will use Monado. This is best done with an OpenXR runtime selector UI like [xr-picker](https://github.com/rpavlik/xr-picker/releases/) which provides the functionality of adding a runtime json manifest in a custom path, and then setting it as active runtime.
> 2. The environment variable XR_RUNTIME_JSON can be set to make OpenXR applications started from just this one shell to use the specified OpenXR runtime. For this, open a second shell and set XR_RUNTIME_JSON to the path of openxr_monado.json such as: `$env:XR_RUNTIME_JSON="$env:USERPROFILE\Downloads\artifacts\install\openxr_monado.json"`. Then start an OpenXR application from this shell like `& $env:USERPROFILE\openxr_loader_windows\x64\bin\hello_xr.exe -G Vulkan2`.
> 
> When the OpenXR application is started, monado's compositor window should open and show two views of the application for the left and right eye.
> 
> To control the remote driver, such as to move the virtual HMD around, run the command `& $env:USERPROFILE\Downloads\artifacts\install\bin\monado-gui.exe remote` and click connect.

**Comment by rvkennedy** [comment]
Thanks @ChristophHaag , I've got Monado building now and using for testing.
