### ISSUE TITLE
Windows build description accuracy

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#18]
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/main/tutorial/1-introduction.rst?plain=1#L214

`Go to the Build menu and select "Build Solution". The projects will be compiled, and the output
	from ``openxr_loader.vcxproj`` should be a library called ``openxr_loaderd.lib``.`

is this still accurate with the switch to fetch dependency?

**Comment by AndrewRichards-Code** [comment]
This is now handled by CMake `FetchContent`, committed in a901f3cb. Closing issue.
