### ISSUE TITLE
Choice of linear algebra library

### ISSUE THREAD

**Issue by rvkennedy** [KhronosGroup/OpenXR-Tutorials#19]
We need a solution for linear algebra. There's a file "xr_linear.h" in the OpenXR SDK which we could use.
We can copy it directly into the project, that obviously separates it from its intended source, plus it's PDX-License-Identifier: Apache-2.0, and copyright Khronos _and_ "Oculus VR LLC" i.e. Meta.
We could add a new minimal header-only lib, or we could use something like glm.

**Comment by rbessems** [comment]
If possible I like using xr_linear.h as it has the right types already supported.
