### ISSUE TITLE
Missing OpenXR intent category and broker permission

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#2]
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/simul-pitch/Chapter2.1_Android/app/src/main/AndroidManifest.xml#L22

```xml
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.LAUNCHER" />
        <category android:name="org.khronos.openxr.intent.category.IMMERSIVE_HMD" />
      </intent-filter>
```

and broker permission

```xml
<uses-permission android:name="org.khronos.openxr.permission.OPENXR_SYSTEM" />
```

**Comment by rvkennedy** [comment]
Unless we also add:

```\<category android:name="com.oculus.intent.category.VR" /\>```

The app will not launch to fullscreen on Quest 2. @rpavlik does this sound correct? Is there a cross-platform way to do this?

**Comment by rbessems** [comment]
@rvkennedy the working group designed:

<category android:name="org.khronos.openxr.intent.category.IMMERSIVE_HMD" />

to be that cross platform way to do this, however not all vendors have implemented this yet. So for now we'll have to add the oculus tag to the manifests manually. I'd add a comment saying that this is a vendor specific string that will not impact other runtimes.

**Comment by rpavlik** [comment]
yeah kind of frustrating but at least the cross-vendor loader works on Quest now, hopefully just a matter of time before the standard metadata does as well.

Actively trying to keep track of and shrink the list of devices that require anything but the standard loader/operations.

**Comment by rvkennedy** [comment]
@rbessems thanks, it looked like this was what was intended. We'll make sure it's clear in the text what all the elements are for.
