### ISSUE TITLE
Simple example in section 2.1 not connecting to OpenXR runtime

### ISSUE THREAD

**Issue by wsherman64** [KhronosGroup/OpenXR-Tutorials#21]
So I've been working through the OpenXR tutorial in as small of steps as I can, as though (and in fact) a naive developer for OpenXR, and I'm only part-way through section 2.1, and have it building, but when running it doesn't connect to my OpenXR runtime (Monado), running on Linux.

I've had to make some changes here and there to the code in order to get it to compile, so it's possible my changes were not correct -- but the original code seems to have some mistakes in it.  One mistake in particular is that there seems to be inconsistent usage of "XrInstance" vs "xrInstance" vs. "instance" and I think even "xr_instance".  I *think* many uses of "XrInstance" should be just "instance" so that is the change I made.

If anyone wants to look at my changes, I put a tar file of my version at:
   [](http://freevr.org/Downloads/openxrTutChap2.1_WRS.tar)

Any place where I made changes to what's in the online tutorial are commented with "WRS".

**Comment by rbessems** [comment]
Hey Bill,

Thanks for going through that, for some reason your URL didn't come
through, can you put a MR on the github repo?

*—*


*Ron Bessems*
Distinguished Engineer
***@***.***
This message and any attachments are intended only for the use of the
addressee and may contain information that is privileged and confidential.
If the reader of the message is not the intended recipient or an authorized
representative of the intended recipient, you are hereby notified that any
use, dissemination or reproduction of this communication is strictly
prohibited and may be illegal. If you have received this communication in
error, notify the sender immediately by return email and delete the message
and any attachments from your system.

**Comment by wsherman64** [comment]
Hmmm, well I entered the URL and then highlighted it and clicked on the link icon, and I thought the syntax looked weird, but figured it must have been correct.

I don't have time now to figure out how to make it an MR, so I'll just enter the link in plain text there:
    http://freevr.org/Downloads/openxrTutChap2.1_WRS.tar

  thanks!

**Comment by rbessems** [comment]
Thanks Bill,

I've created the MR against chapter 2
<https://github.com/KhronosGroup/OpenXR-Tutorials/pull/22> files but I'm
not sure your base matches what is currently on github.  Can you have
another look at their files?

*—*


*Ron Bessems*
Distinguished Engineer
***@***.***
This message and any attachments are intended only for the use of the
addressee and may contain information that is privileged and confidential.
If the reader of the message is not the intended recipient or an authorized
representative of the intended recipient, you are hereby notified that any
use, dissemination or reproduction of this communication is strictly
prohibited and may be illegal. If you have received this communication in
error, notify the sender immediately by return email and delete the message
and any attachments from your system.
