### ISSUE TITLE
Local space

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#23]
1. The space section is missing nuances of re-localization that might occur.

2. https://github.com/KhronosGroup/OpenXR-Tutorials/blob/main/tutorial/4-actions.rst?plain=1#L14

Spec defines local space as:

> The LOCAL reference space establishes a world-locked origin, gravity-aligned to exclude pitch and roll, with +Y up, +X to the right, and -Z forward. This space locks in both its initial position and orientation, which the runtime may define to be either the initial position at application launch or some other calibrated zero position.

The tutorial says:

> the XR hardware’s “local” space - either the headset’s starting position or some other world-locked origin.

We should probably clarify this a bit.

**Comment by AndrewRichards-Code** [comment]
Chapter 3.2 Create Reference Space discusses the types of space.
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/1432c96b141d02dcc53c78bdbb6830fa87b32c65/tutorial/3-graphics.rst?plain=1#L590
At present the tutorial code does not handle any reference space changes.

**Comment by AndrewRichards-Code** [comment]
Do we want to discuss reference space changes? The hello_xr program in the OpenXR-SDK-Source repo doesn't react to this event. What do we think is best?

https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/8270b15bcb676f26fbb5e6aa96e02712f80b7ad7/src/tests/hello_xr/openxr_program.cpp#L694-L725

https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrEventDataReferenceSpaceChangePending.html

**Comment by rbessems** [comment]
Let's leave it be.
