### ISSUE TITLE
Tabs and Spaces

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#26]
It appears the source code is mixing tabs and spaces.

indentation = 4 spaces ... Not tabs.

**Comment by AndrewRichards-Code** [comment]
This is now resolved by this:
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/b0d6ae507a46770d97dfb54d35d7415f04e3aed6/.clang-format#L3
All chapter code is updated to reflect this change in the `.clang-format` file.
