### ISSUE TITLE
ABI Filter should allow for x86-64 as well

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#3]
Currently the ABI filter is set for ARM, there are devices out there that are not ARM based

https://github.com/KhronosGroup/OpenXR-Tutorials/blob/simul-pitch/Chapter2.1_Android/app/build.gradle#L14

```gradle
abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
```

**Comment by AndrewRichards-Code** [comment]
Commit https://github.com/KhronosGroup/OpenXR-Tutorials/commit/9e08aae2f05338e98b2e2910b6f59f006a06d063 removes the `abiFilters` from the `app/build.gradle` files.
