### ISSUE TITLE
Discuss aim vs grip pose.

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#31]
It might also be good to have some discussion of the difference between aim and grip pose ; why they both exist; what the different purposes are, etc.

**Comment by BastiaanOlij** [comment]
I'm not sure where I saw them, whether they are in the docs or not, but a picture speaks a thousand words here. Having some images of different controllers and where the aim, grip and palm poses on those are will do wonders.

**Comment by rvkennedy** [comment]
@rbessems can we use images wholesale from the spec?

**Comment by rbessems** [comment]
probably do want to host the images with the tutorial, don't hotlink.

**Comment by rvkennedy** [comment]
This is now described in Chapter 4, along with the image, which is hosted on-site.
