### ISSUE TITLE
Why Actions and explain sub action paths.

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#35]
If I were to write it I'd begin with a preamble which would frame the action system. i.e. why does it exist? What problems is it trying to solve? Why does it need to be so abstract and weird? Why can't I just access controller hardware directly etc...? The questions that developers may have going into this weird and unconventional system if they have NEVER seen it before. I think its crucial for developer understanding to get them into the right head space and framing for this and for that we need to give context.

There is also no mention of subaction paths, which is a huge point of confusion from developers. I believe that should also be given some context (motivation and history), and potentially an example as to why it would be used. 

I'd prefer that the examples of actions given were not just controller button actions, but rather game / app actions like "teleport" "interact" "shoot" "jump" etc...

**Comment by rpavlik** [comment]
See my writeups on #30 that probably should have gone here instead.

**Comment by rvkennedy** [comment]
Thanks @rpavlik , it's starting to come into focus for me. I'll update the text provisionally in advance of the meeting on 1st August.

**Comment by rbessems** [comment]
some more details from the godot project:

https://docs.godotengine.org/en/stable/tutorials/xr/xr_action_map.html

**Comment by rbessems** [comment]
tentative closing
