### ISSUE TITLE
NDK Version

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#4]
NDK 4.2.2 is pretty old and I believe throwing warnings in newer Android Studio versions. Let's get some more recent in here.

**Comment by AndrewRichards-Code** [comment]
Commit https://github.com/KhronosGroup/OpenXR-Tutorials/commit/9e08aae2f05338e98b2e2910b6f59f006a06d063 updates the project to use Gradle 7.5 and AGP 7.4.2. NDK version is still '23.1.7779620', or should match it with OpenXR-SDK-Source.
https://github.com/KhronosGroup/OpenXR-SDK-Source/blob/d6b6d7a10bdcf8d4fe806b4f415fde3dd5726878/src/tests/hello_xr/build.gradle#L30
