### ISSUE TITLE
Questionable sentence about multiple XrInstance in Concepts

### ISSUE THREAD

**Issue by ChristophHaag** [KhronosGroup/OpenXR-Tutorials#41]
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/c3b73f2a82675f0e4d23b5b505b7a1ed766bf527/tutorial/1-introduction.rst#L64-L65

> If the Runtime supports it, you might have more than one Instance at a time, if more than one XR device is in use.

See also

https://registry.khronos.org/OpenXR/specs/1.0/loader.html#functional-flow

> The loader supports a single XrInstance at a time in order to avoid tracking handle values and their relationship to the LoaderInstance. Every XR function call is assumed to be for the single XrInstance that has been created. This enables the loader to work with future extensions and handle types without change.

**Comment by AndrewRichards-Code** [comment]
Hi @ChristophHaag, thank you for the question. I will speak with @rvkennedy to get a bit more information.
I found an old Siggraph talk/slide (pre-dating the 1.0 specification) which might be the possible origin of this.
https://www.khronos.org/assets/uploads/developers/library/2018-siggraph/04-OpenXR-SIGGRAPH_Aug2018.pdf

**Comment by rpavlik** [comment]
The standard does *not* allow it. That was removed before 1.0. The presentation cited predates OpenXR 1.0.

Please check with the **standard** before making assertions.

**Comment by rvkennedy** [comment]
The origin of it was the 1.0 spec text in the link above. I'm removing the text to avoid any definitive statement on this.
