### ISSUE TITLE
Create Diagrams for XrSpaces 

### ISSUE THREAD

**Issue by AndrewRichards-Code** [KhronosGroup/OpenXR-Tutorials#45]
Create 3D diagrams for  XrSpaces to be used in Chapter 3.

**Comment by AndrewRichards-Code** [comment]
Reference #66 too!

**Comment by rbessems** [comment]
I think the image is probably good for the broad idea what view space is but should not be used for the actual pose of the view space. 

Maybe slice off most of the body to keep the image reasonably sized.

**Comment by rvkennedy** [comment]
What would you like to see @rbessems? I think we're looking for a non-neutral pose. But unless we're looking at the back of the head, the Z-axis will be pointing away from the viewer.

**Comment by rbessems** [comment]
So the feedback that came said move the center forward more right between the eye, it almost looks as if it is inside the head currently.

**Comment by rbessems** [comment]
Also make sure that x, y and z are either labeled in the graph, or clearly labeled in the tutorial overall.

**Comment by rvkennedy** [comment]
![ViewSpace](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/8841b512-d8e3-4f8b-ab2b-20ade6841830)

**Comment by rvkennedy** [comment]
Here the centre has been placed between the eyes at the front of the head. The Z-axis is wholly enclosed but still quite clear I think. Axis labels have been added, and the torso has been cropped.

**Comment by rvkennedy** [comment]
Final (?) images:
![LocalSpace](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/ae91431e-57ab-4bf8-b5cb-0d9cb7b03e33)
![StageSpace](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/3089ce2e-de26-4d87-9c4f-5c8bde76b3de)
![ViewSpace](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/ed2ca654-b1bc-42ae-8882-3c0b198f0458)

**Comment by rbessems** [comment]
I'm not sure I like the local space graphic. I'll post these in the W.G. to get comments

**Comment by rvkennedy** [comment]
Time is short so I hope we can get some clear suggestions. One option would be to swap the "initial" and "current" head positions, then the Z axis would be more visible.

**Comment by rvkennedy** [comment]
Possible alternative: ![LocalSpace](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/a1819a9d-74c0-4fdc-9c0f-198df237bc57)

**Comment by rbessems** [comment]
I like the alternative.

And the group likes that stage space drawing you have above.

**Comment by rvkennedy** [comment]
this is the stage space with no figure.
![StageSpaceOnly](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/3081af0b-8aaa-4c9b-be93-b7cfa2997881)
