### ISSUE TITLE
Chapter 2 build fails on Linux looking for "hDC" field

### ISSUE THREAD

**Issue by wsherman64** [KhronosGroup/OpenXR-Tutorials#46]
I did a test this evening from the current github clone on my Linux system, and encountered an error building Chapter 2 where:
```error: ‘struct ksGpuWindow’ has no member named ‘hDC’```
And I found that in "gfxwrapper_opengl.h" this field only exists for MS-Windows, so the correct value needs to be selected for the Linux build.

  Bill

**Comment by AndrewRichards-Code** [comment]
Hi Bill, This issue should be resolved by commit 9e498d5c2afc0ab8d545d173b40f998f1022d426.
