### ISSUE TITLE
Comments -- need more of them

### ISSUE THREAD

**Issue by wsherman64** [KhronosGroup/OpenXR-Tutorials#47]
Given that this is a tutorial, I think it's important that there be an abundance of comments in the code explaining (perhaps in high detail) exactly what is going on.

In particular I think each and every function should have a comment that describes what that function/method does, how it's used, and probably even why it's needed.

Plus I'd like to see more comments throughout the code in general.

**Comment by rvkennedy** [comment]
Plenty of comments now.
