### ISSUE TITLE
Logos for DirectX 11 and DirectX 12.

### ISSUE THREAD

**Issue by AndrewRichards-Code** [KhronosGroup/OpenXR-Tutorials#48]
For the graphics API selection tabs, we have logos relating to their respective APIs. Khronos APIs are well-supported, but at present we don't have a good solution for Microsoft's DirectX APIs.
We are already in discussion with Microsoft for the usage of the Windows 10 logo, but we should also ask what would be best to use for the DirectX APIs.

**Comment by rbessems** [comment]
done
