### ISSUE TITLE
SVG Icons: feedback

### ISSUE THREAD

**Issue by rvkennedy** [KhronosGroup/OpenXR-Tutorials#49]
I've had an icon made as a test, this is to represent an XR hand controller for Chapter 4.

![HandsetIcon](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/493944/e315daf0-562b-40a6-8ddf-ef08be34fdbd)

You can see it at a more usual size in-place at [Chapter 4](https://openxr-tutorial.simul.co/4-actions.html)

Please post any feedback on general design, colour (this one is grey but most will use pastels) etc.

**Comment by AndrewRichards-Code** [comment]
I think it looks great. We will need svg logos for the other chapters for a consistent look. Do you have designs in mind?

**Comment by rbessems** [comment]
Nice, I like this design.
