### ISSUE TITLE
Navigation button (hamburger menu) does not respond to mouse clicks or touch events

### ISSUE THREAD

**Issue by dennyronngren** [KhronosGroup/OpenXR-Tutorials#50]
Hi,

The navigation button in mobile view does not seem to respond to mouse clicks or touch events.

Tested with Chrome 116 and Edge 116.

![image](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/16424533/9704825c-3d45-4c33-ae49-18528706a7be)

**Comment by rvkennedy** [comment]
Fixed in b70602235d9f3e28d3b6a945fb1400e86c0ef154
