### ISSUE TITLE
Code blocks renders in front of top navigation

### ISSUE THREAD

**Issue by dennyronngren** [KhronosGroup/OpenXR-Tutorials#51]
Hi, while going through the tutorial, I did found that the code examples are rendered on top of the top menu, rest of the content seems to go behind the top menu.

I don't know what the design that was decided, is the top meny supposed to be sticky or is it supposed to scroll with the text? Just wanted to put this here for discussion.

Tested on current Edge.

![image](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/16424533/9b2efd79-0238-4daa-b5db-46c5530ed385)

**Comment by AndrewRichards-Code** [comment]
This is now fixed.
