### ISSUE TITLE
Two issues with Linux build (09/18/23)

### ISSUE THREAD

**Issue by wsherman64** [KhronosGroup/OpenXR-Tutorials#52]
Hey all,

I did a rebuild today on the Linux branch of the github repo, and I encountered two issues.

1) There's still a hard-coded directory for Roderick in the "Chapter2/main.cpp" code -- the logic implies that it should be overridden, but that doesn't seem to happen, and so since I don't have that path, it errors out.

2) When building Chapter4, I get this error:
[ 66%] Building CXX object CMakeFiles/OpenXRTutorialChapter4.dir/home/wrs1/Apps/OpenXR/Tutorial/SimulTut/OpenXR-Tutorials_git20230918/Common/OpenXRDebugUtils.cpp.o
[ 68%] Linking CXX executable OpenXRTutorialChapter4
GLSL ../Shaders/VertexShader.glsl
make[2]: Vulkan_GLSLANG_VALIDATOR_EXECUTABLE-NOTFOUND: Command not found
make[2]: *** [CMakeFiles/OpenXRTutorialChapter4.dir/build.make:219: OpenXRTutorialChapter4] Error 127
make[2]: *** Deleting file 'OpenXRTutorialChapter4'
make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/OpenXRTutorialChapter4.dir/all] Error 2

**Comment by rpavlik** [comment]
Does #40 work for you? I overhauled it rather substantially to get it to actually build on my machines, but after doing that I could run example 5 against monado locally.

**Comment by rvkennedy** [comment]
Are these issues still present? I can't find a hardcoded path.

**Comment by rpavlik** [comment]
yeah I partially redid the build system so it should be fixed now, just hoping for Bill to verify.
