### ISSUE TITLE
Graphics Detection

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#55]
The current method of graphics api selection is fairly static and will fail to run if the underlying device doesn't support whatever was hard coded even though the code supports alternate API's.

Ideally the code has an ordered set of graphics API's and selects the first from that list that the underlying runtime supports.

**Comment by rvkennedy** [comment]
It's doable and not difficult. We were thinking the tutorial user would have the specific API in mind that they want to use.

**Comment by AndrewRichards-Code** [comment]
Build time is fine. Default to Vulkan in CMake.

**Comment by AndrewRichards-Code** [comment]
#69 addressed and fixes this.
