### ISSUE TITLE
Layout/Style Polishing

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/OpenXR-Tutorials#60]
Several issues were noted during the project call. This issue is intended to be a complete listing of the issues

1. The OS icons need to be centered in the tab
2. Remove the space (horizontal & vertical) tabs
3. Hamburger menu does not work
4. The header should not be present in phone landscape more (too few lines of text)
5. Intermediate small width wraps the the graphics tabs. A little narrower removes header. It would be better to set the breakpoint so the intermediate small width has no header. This may also fix ^4
6. "Space Invaders" icon is probably protected, so that needs to be changed (^3 Chapter icon)
7. Footer needs to change as follows
    1. Remove "&copy; Copyright" from existing statement
    2. Copyright and license for logos: OpenGL, OpenGL|ES, Vulkan, and the DirectX logos
    3. Copyright and license for document 
        1. Document: &copy; 2023, The Khronos Group. License: CC-BY 4.0 International 
        2. Code (when removed from document): (c) 2023, The Khronos Group. License: Apache 2.0
    4. Order of display:
        1. &copy; 2023, The Khronos Group. License: [CC-BY 4.0 International](https://creativecommons.org/licenses/by/4.0/deed.en)
        2. Code when removed from document: &copy; 2023, The Khronos Group. License: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
        3. "OpenXR®" and the OpenXR® logo are trademarks owned by The Khronos Group Inc. and are registered as a trademark in China, the European Union, Japan and the United Kingdom.
        4. Vulkan and the Vulkan logo are registered trademarks of the Khronos Group Inc.
        5. OpenGL® and the oval logo are trademarks or registered trademarks of Hewlett Packard Enterprise in the United States and/or other countries worldwide.
        6. OpenGL is a registered trademark and the OpenGL ES logo is a trademark of Hewlett Packard Enterprise used by permission by Khronos.
        7. Microsoft DirectX, Microsoft DirectX11, and Microsoft DirectX12 are trademarks owned by Microsoft.
8. Section for credits - include Simul, testers (need permission to list names), GitHub (for updates)

**Comment by rvkennedy** [comment]
Done.
