### ISSUE TITLE
Interaction Profiles, Symantic Actions and Sub Action Paths

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#61]
We need to demonstrate 3 more things: Binding to multiple Interaction Profiles, Semantic action names and sub action path bindings.

* Add a 2nd interaction profile to the tutorial code for the Oculus Touch controller.
* Add new XrAction named "Change Color"  ->  will cycle through a list of colors of the cube that is currently being 'touched'.
* Add new XrAction named "Spawn Cube"   -> Spawns cube in the current location.
* On the simply controller profile demonstrate how to use a sub action path by binding 'grab' to the right handed simple controller trigger and 'change color' to the left handed simple controller 'trigger'.
* On the oculus touch there are enough buttons to bind the two new actions to buttons of your choice.

If we need to break chapter 4 into multiple chapters that is OK.

**Comment by rvkennedy** [comment]
Thanks Ron.

We do actually show a profile for the Oculus Touch in Ch4, is this not what you meant?

I've added m_ActionChangeColor on the trigger as a boolean action (we didn't have one of these).
I've added m_spawnCubeAction without subAction paths, as all others have them so far. It's bound to the A button on the right touch controller.

Code works well, I'll add some text.

**Comment by rbessems** [comment]
Awesome, that is what I meant, so great it already there!
