### ISSUE TITLE
Android Studio warning for main.cpp

### ISSUE THREAD

**Issue by rvkennedy** [KhronosGroup/OpenXR-Tutorials#70]
“This file does not belong to any project target” in Android Studio. Seems everybody gets this warning for main.cpp.

**Comment by AndrewRichards-Code** [comment]
This is solely an Android Studio issue. I have just tested this and the project compiles. Full rebuilds, and re-opening the editor should resolve this issue.

**Comment by rvkennedy** [comment]
Do full rebuilds resolve the issue?

**Comment by AndrewRichards-Code** [comment]
I have dug into this a little more. Go to `File > Invalidate Caches...` and select `Invalidate and Restart` in the popup window.

**Comment by AndrewRichards-Code** [comment]
Commit d67281e resolves this issue by adding an explanation to the Chapter 1 text to fix this Android Studio issue.

**Comment by rvkennedy** [comment]
A more lightweight fix for this issue is:

right-click on the top-level folder of the project in the ``Project`` panel, select ``Mark Directory as >``, and click the option ``Sources Root``.

I've merged this into the text.
