### ISSUE TITLE
Create ZIP files per chapter using GitHub Actions

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#72]
Create ZIP files per chapter using GitHub Actions

**Comment by AndrewRichards-Code** [comment]
Commit ffab8fa adds the .sh and .yaml files for this GitHub action, which should build the zip archive to an `eoc-archs` folder per chapter. I don't have Linux to test the bash script thoroughly, but it should work (brave words). I will also need to dig into GitHub actions to get things set up correctly.

**Comment by AndrewRichards-Code** [comment]
Commit f0253df disables uploads to GitHub release

**Comment by AndrewRichards-Code** [comment]
This doesn't remove the // XR_DOCS_TAG_ from the sources.

**Comment by AndrewRichards-Code** [comment]
Commit babc890 adds a Python script that removes the XR_DOCS_TAG_ lines from the cpp and CMake files.

**Comment by AndrewRichards-Code** [comment]
Commit 06b6ca5 and 1bef7d8 builds the end of chapter archives in CMake and puts them in the `build/eoc_archs` folder.

**Comment by AndrewRichards-Code** [comment]
Commit f27ae6b updates `build-eoc-archs.yml` to build and upload the archives to release.

**Comment by rvkennedy** [comment]
Tested, closing the issue.
