### ISSUE TITLE
workflow generated site does not match

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#75]
The site generated by the workflow is different from what is on simul's domain.

On first glance: Missing icon chapter 6, top tabs are not centers and size differently.

**Comment by AndrewRichards-Code** [comment]
I've downloaded and extracted the `site.tar.gz` from the v0.0.1 tag (ff42e5e) and opened the pages in Chrome, Firefox and Edge. The website is rendering fine in all three browsers. I'm not sure what could be causing the issue here.

**Comment by rbessems** [comment]
Either way it's now resolved.
