### ISSUE TITLE
chapter indent different from sub-chapter indent

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#76]
chapter indent different from sub-chapter indent

for example chapter 5 header and icon are further indented compared to the 5.1 sub-chapter.

![Screenshot from 2023-11-13 15-24-36](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/77022116/9cd75b09-71db-483b-b3dd-5ae0fce52a35)

**Comment by rvkennedy** [comment]
Fixed in css with margin-left:-32px in section >h1:before.

**Comment by rbessems** [comment]
There is still an offset on the index page https://www.openxr-tutorial.com/index.html

**Comment by rvkennedy** [comment]
Fixed with specific css for openxr-tutorial section - as this has no icon.
