### ISSUE TITLE
links are not clickable

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#78]
take the build tag as an input to the build system
then use that to link to the chapter zip files on github.

for example: https://github.com/KhronosGroup/OpenXR-Tutorials/releases/download/v0.0.2/Chapter1.zip

**Comment by rbessems** [comment]
Looks like if the link is formatted as follows:

https://github.com/KhronosGroup/OpenXR-Tutorials/releases/download/v0.0.5/Chapter3.zip

it does work directly.

**Comment by AndrewRichards-Code** [comment]
Commit 28be71e updates the rst `:git_release:` tag to the use link that automatically downloads the zip archive.
@rbessems, Thank you so much for the help.

**Comment by AndrewRichards-Code** [comment]
Unfortunately, the GitHub Actions are still queued: 
https://github.com/KhronosGroup/OpenXR-Tutorials/actions

**Comment by AndrewRichards-Code** [comment]
All those pending GitHub Actions are now finished, and the site is updated. I have just tried the links and was able to download the archives.

**Comment by rbessems** [comment]
looks good.
