### ISSUE TITLE
Footer Text Needs Adjusting

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/OpenXR-Tutorials#79]
This issue deals with multiple items in the footer of each page.

- The footer text is a bit too large (currently same size as body text - 14px) and should be reduced (not shown below).
- There should also be a header (not in numbering sequence) for this section to make it clear that it is not content body. 
- A couple of the text items need to be changed
  - The first line needs to be copyright of the material
  - The external ownership needs to be put into a separate paragraph.
- It would help to reorganize the text - suggested structure is below.

Suggest replacement text

### Legal Notice
© 2023, The Khronos Group. [Creative Commons International 4.0 BY Attribution](https://creativecommons.org/licenses/by/4.0/deed.en). Code is licensed as [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). 

The OpenXR Tutorial is owned and operated by [The Khronos Group Inc.](https://www.khronos.org/) Khronos [Legal Notices](https://www.khronos.org/legal/), [Privacy Policy](https://www.khronos.org/legal/privacy), and [Code of Conduct](https://www.khronos.org/about/code-of-conduct) apply.

"OpenXR" and the OpenXR logo are trademarks owned by The Khronos Group Inc. and are registered as a trademark in China, the European Union, Japan and the United Kingdom. Vulkan and the Vulkan logo are registered trademarks of the Khronos Group Inc. 

OpenGL® and the oval logo are trademarks or registered trademarks of Hewlett Packard Enterprise in the United States and/or other countries worldwide. OpenGL is a registered trademark and the OpenGL ES logo is a trademark of Hewlett Packard Enterprise used by permission by Khronos. 

Microsoft DirectX, Microsoft DirectX11, and Microsoft DirectX12 are trademarks owned by Microsoft.

**Comment by AndrewRichards-Code** [comment]
Commit 7b8d8ba should resolve this issue with the footer text. Below is an image of how the footer is rendered in Chrome.
![image](https://github.com/KhronosGroup/OpenXR-Tutorials/assets/40760786/313ad2a1-c516-42d9-9b18-8dd168b369f0)

**Comment by rbessems** [comment]
The paragraph spacing is unusually large,... what happened?

**Comment by AndrewRichards-Code** [comment]
I am using `<br>` to add new lines. I will see if there's a way to control the sizing.

https://github.com/KhronosGroup/OpenXR-Tutorials/blob/28be71efab8cc57539d370a54ea870f27b65f6bf/tutorial/tutorial_sphinx_theme_1/footer.html#L27-L33

**Comment by rbessems** [comment]
Awesome much better. Thanks.
