### ISSUE TITLE
Place Icons before chapter numbers

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#8]

**Comment by rvkennedy** [comment]
Done as far as it goes, but as discussed, we may need to create svg icons instead of font icons in the text.

**Comment by AndrewRichards-Code** [comment]
From the OpenXR Tutorial Review Meeting on 2023/08/22 at 14:00 UTC, we are switching to SVG icons before chapter numbers.
I believe Simul will look into finding a graphics designer for these.

**Comment by rvkennedy** [comment]
First icon is implemented, a hand controller icon for Ch4. Others to follow.

**Comment by rvkennedy** [comment]
Tricky to get these icons into the sidebar TOC, as these don't have individual html id's. We may need to do this with JavaScript.
