### ISSUE TITLE
android api layers

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#80]
Add a JSON file as attached to the APK assets

[openxr.zip](https://github.com/KhronosGroup/OpenXR-Tutorials/files/13355718/openxr.zip)

And when building the loader in cmake we have the following:

```
OPTION(USE_OPENXR_LAYERS "Use OpenXR layers" ON)
set(BUILD_ALL_EXTENSIONS ON CACHE INTERNAL "Build loader and layers with all extensions")
set(BUILD_TESTS OFF CACHE INTERNAL "Build tests")
set(BUILD_CONFORMANCE_TESTS OFF CACHE INTERNAL "Build conformance tests")
set(BUILD_API_LAYERS ${USE_OPENXR_LAYERS} CACHE INTERNAL "Use OpenXR layers")
FetchContent_Declare(
        oxr
        URL https://github.com/KhronosGroup/OpenXR-SDK-Source.git)
```

**Comment by AndrewRichards-Code** [comment]
I have just tested this on a Meta Quest 2 and was able to load the `XR_APILAYER_LUNARG_core_validation` layer. I will update the chapter 6.3 text.

**Comment by AndrewRichards-Code** [comment]
Commit 859d1d9 updates the chapter 6.3 text to include Android's usage of API layers.
