### ISSUE TITLE
need a way to link into graphics/os selected tabs

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#82]
When creating links to the tutorial people will want to be able to link to OS / GFX specific pages. 

For example
https://openxr-tutorial.com/1-introduction.html#environment-setup?os=Android&gfx=Vulkan would be acceptable, though a  more SEO friendly approach might be better.

**Comment by AndrewRichards-Code** [comment]
Commits 4fdaa3a, dbfb508, 7377e1e and 36ee8d8 through e9c0876 add URL parameters. You can manually edit the URL or click the tabs to update the cookies, which saves the user's selection choices in the URL.

**Comment by rvkennedy** [comment]
While this now works, I'm a bit dubious about it. We rewrite the address bar to add the parameters, but it's a bit ugly. @rbessems  how about we support the params but don't add them if they aren't there?

**Comment by rvkennedy** [comment]
The solution we've implemented, there's a "share" button at the top-right of each page, which copies to the clipboard the current page URL, adding in the parameters if not already present.

**Comment by rbessems** [comment]
Yes that is an option. It's a bit cumbersome and I'm not 100% sold on the paragraph symbols in every heading. Let's discuss tomorrow.

This also is making me wonder how well this text is discoverable by the Google spider. I'll open a separate ticket for that.

**Comment by rvkennedy** [comment]
I agree, the permanent para symbols are ugly. I've made it so they are invisible until hovered.
Hidden text is available to all search spiders and not ranked negatively unless flagged as manipulative, which would not be correct in this case.
https://stackoverflow.com/questions/21997663/hidden-text-negative-for-google-spiders#21997688
