### ISSUE TITLE
Discoverability by the Google spider

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#86]
With the OS and GFX selectors at the top doing some javascript magic I am a bit worried about the discoverability for search engines. 

Possible solutions are a site map providing links into all the various bits of text. HOWEVER that makes a single URL appear with different text which will confuse the whole indexing.

We have to rethink how the URL appear for OS/GFX for SEO purposes.

.htaccess and some smart redirects might do the trick here. I'll inquire what server we are running.

**Comment by rvkennedy** [comment]
Hidden text is available to all search spiders and not ranked negatively unless flagged as manipulative, which would not be correct in this case.
https://stackoverflow.com/questions/21997663/hidden-text-negative-for-google-spiders#21997688

**Comment by rbessems** [comment]
which it may be visible, the search engine will not be able to link to the correct page.

**Comment by rvkennedy** [comment]
Not sure I can conceive of an ideal solution to that, but I'm open to suggestions.

**Comment by rbessems** [comment]
I think structuring our links as follows:

https://openxr-tutorial.com/<chapter>/<gfx>/<os><#anchor>

https://openxr-tutorial.com/graphics/vulkan/linux

with a  site map should do the trick. I've confirmed we are using Apache so modRewrite or rewritemap
(https://httpd.apache.org/docs/current/rewrite/rewritemap.html) are options.

**Comment by rvkennedy** [comment]
Excellent, I'll follow up with them.

**Comment by rbessems** [comment]
Note: the buttons at the top should probably use the links to the pages

**Comment by rvkennedy** [comment]
In tutorial/
Added sitemap.xml with all combinations.
Added robots.txt to reference sitemap.
Added tutorialmap to remap URLs from path to parameter format.

**Comment by rvkennedy** [comment]
In conf.py, I've added a function that generates a text sitemap. This would then need to be correctly deployed. The output is:
[sitemap.txt](https://github.com/KhronosGroup/OpenXR-Tutorials/files/13491021/sitemap.txt)

**Comment by rvkennedy** [comment]
@rbessems the structure can be changed as follows:
By using Sphinx's variant system, we can generate eight versions of the site and put them in appropriate subfolders. At the root would be only a redirect, or possibly a version of the index. We'll need to experiment with this.
I have asked an SEO expert for an opinion on whether the current structure or the alternate is best for page discoverability and ranking. But if you have anyone on the Khronos side you want to consult with that will help as well.

**Comment by rbessems** [comment]
OS / GFX selection
==================

Remove the tabs, uses selects gfx/os on index page.
Consider adding a dropdown instead of the tabs with a table of OS/GFX entries.

Add table with

* Android OpenGLES
* Android Vulkan
* Linux OpenGL
* Linux Vulkan
* Windows DX11
* Windows DX12
* Windows OpenGL
* Windows Vulkan


Pages
=====

* index.html
* search.html
* android/opengles/[page_name].html
* android/vulkan/[page_name].html
* linux/opengl/[page_name].html
* linux/vulkan/[page_name].html
* windows/dx11/[page_name].html
* windows/dx12/[page_name].html
* windows/opengl/[page_name].html
* windows/vulkan/[page_name].html

page_name can be

* introduction
* setup
* graphics
* interactions
* extensions
* next_steps


Creation
========

The different OS & GFX combination pages should be generated automatically from the single 
source topics much like is currently done for the cookie workflow. This should happen
automatically that can be ran in a github action, again must like the current flow.

**Comment by rvkennedy** [comment]
I have built an initial version with the new structure at [https://openxr-tutorial.simul.co/](https://openxr-tutorial.simul.co/).
There are eight sub-sites, and a root site which contains only the index. The Platform/API is selectable with a dropdown at top-right, or from the main index page.

- It's unclear what should appear on the left nav panel at the root site. The current links don't have platform/API so don't lead anywhere.
- There isn't a good user journey from the main index to the subsites - it's confusing.
- The current wording will need to be changed to make clear the new site structure.

**Comment by rbessems** [comment]
Happy new year Roderick,

* I'd advocate for the the default to be Android / Vulkan ( most standalone headsets are this combination )
* Since the root pages still have the drop down on the top right, set this to Android Vulkan and match the links in the nav panel on the left to that combination

**Comment by rvkennedy** [comment]
Happy New Year Ron!
I've made the default Android/Vulkan, so the root site displays this and links to its sub-pages on the sidebar.
At the moment the only route back to the root site is to click the logo at top-left. However this may be unwanted.
The root site's index page contains no content that the subsites don't. So perhaps this link should take us to the index of the current subsite with no loss of functionality.

**Comment by rvkennedy** [comment]
Additional questions:
* what should search do on the root site? Search Android/Vulkan?
* What do we want to happen when the user selects a platform from the root site index? Just now, it reloads that page, which then contains the contents table of the subsite. But that might feel a bit clunky.

**Comment by rvkennedy** [comment]
Closed as the site reorg is complete.
