### ISSUE TITLE
https://github.com/KhronosGroup/OpenXR-Tutorials/blob/main/tutorial/images/OpenXR_500px_Feb17.png

### ISSUE THREAD

**Issue by rbessems** [KhronosGroup/OpenXR-Tutorials#87]
appears as a white/empty image.

**Comment by rvkennedy** [comment]
Where is this used?

**Comment by rbessems** [comment]
the readme

**Comment by AndrewRichards-Code** [comment]
Sorry, I only tested the README in dark mode. I'll get this fixed.

**Comment by AndrewRichards-Code** [comment]
Commit dab81f9 adds functionality for both light and dark mode logos in README.
Based on this blog post from GitHub: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

Changes:
```
![image](tutorial/images/OpenXR_500px_Feb17_White.png#gh-dark-mode-only)
![image](tutorial/images/OpenXR_500px_Feb17_RGB.png#gh-light-mode-only)
```
