### ISSUE TITLE
Hamburger Error

### ISSUE THREAD

**Issue by DR-xR** [KhronosGroup/OpenXR-Tutorials#89]
When I reduce my browser (Firefox, latest release) to the minimum width or display the site (https://openxr-tutorial.com/index.html) on a mobile device the left menu reduces to a hamburger. Unfortunately, the hamburger is non-functional. The cursor changes to a pointer (desktop), but there is no response when clicked. There is also no response on a mobile device.

Looking at the debugger, it appears that there is no event (either explicit or implicit [anchor-tag]) associated with the symbol and the cursor change is just through CSS.

**Comment by rvkennedy** [comment]
Fixed again. Seems a bad merge may have deleted the code.
