### ISSUE TITLE
Site Content Error when No Cookies

### ISSUE THREAD

**Issue by DR-xR** [KhronosGroup/OpenXR-Tutorials#90]
If cookies are disabled, then the site content is incorrect. No graphics or OS-specific information is displayed. This can be seen in section 1.3 where there is only 1 paragraph and not anything else. Other sections throughout the site have similar problems.

This presents a problem with SEO as the Google indexer (described at https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics) works from a rendered copy of the page without cookies.

**Comment by rvkennedy** [comment]
I guess we have to default to showing all the content if cookies are disabled.

**Comment by rvkennedy** [comment]
This is done. If cookies are blocked, all content will be shown. Obviously this is intended for crawlers: users will need to allow same-site cookies.
