### ISSUE TITLE
Sphinx error when building documentation

### ISSUE THREAD

**Issue by wsherman64** [KhronosGroup/OpenXR-Tutorials#92]
When I try to build the tutorial from a "git clone" copy of the repo, and I have `XR_TUTORIAL_BUILD_DOCUMENTATION` turned `ON`, then I get this error message early in the build (with VERBOSE=1):
```
[  1%] Generating documentation with Sphinx
cd /home/wrs1/Apps/OpenXR/Tutorial/SimulTut/OpenXR-Tutorials_git20231201/tutorial && /home/wrs1/.local/bin/sphinx-build -a -c /home/wrs1/Apps/OpenXR/Tutorial/SimulTut/OpenXR-Tutorials_git20231201/tutorial -b html /home/wrs1/Apps/OpenXR/Tutorial/SimulTut/OpenXR-Tutorials_git20231201/tutorial /home/wrs1/Apps/OpenXR/Tutorial/SimulTut/OpenXR-Tutorials_git20231201/tutorial/../openxr-tutorial -D html_baseurl=https://openxr-tutorial.simul.co/
Running Sphinx v3.2.1
openxr_tutorials_git_tag_py is v0.0.0

Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')
```
I'm not sure what the `myst_parser` is, but is there a way for me to look for it, or is it because my version of Sphinx is too old?

Regardless, I wonder if maybe once deployed we might want to have the default of `XR_TUTORIAL_BUILD_DOCUMENTATION` be `OFF`.

   Bill

**Comment by rvkennedy** [comment]
I've defaulted XR_TUTORIAL_BUILD_DOCUMENTATION  to OFF.
But also added some text to the Readme.md explaining how to set up to build with Sphinx.
```pip install myst-parser ```will fix this particular error.
