### ISSUE TITLE
Documentation build error with missing Vulkan

### ISSUE THREAD

**Issue by pfontain** [KhronosGroup/OpenXR-Tutorials#97]
When I run the build command a second time with documentation build enabled, I get an error regarding Vulkan not being available
```
> cmake ..\OpenXR-Tutorials\ -DXR_TUTORIAL_BUILD_DOCUMENTATION=ON"
...
-- Enabling OpenGL support
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
CMake Error at C:/Users/Nemes/dev/openxr-tutorials-workspace/build/Chapter1/openxr/src/CMakeLists.txt:88 (message):
  Vulkan headers not found


-- Configuring incomplete, errors occurred!
```

My workaround has been to pass the CMake variable BUILD_ALL_EXTENSIONS as TRUE. I amended the instructions to reference this in this branch https://github.com/pfontain/OpenXR-Tutorials/tree/sphinx-do-not-build-extensions .

If the Vulkan stuff is required for the documentation build, I think we should be explicit about it somewhere.

I haven't figured out why this only happens the second time around.

**Comment by AndrewRichards-Code** [comment]
Hi @pfontain,

We don't expect end-users of the website to build the repository with `"XR_TUTORIAL_BUILD_DOCUMENTATION=ON"`, as this is used to generate the HTML website. However, this build method is specified in our `README.md`, and therefore I have updated it with your changes from your fork.
Thank you for all your help.
